# Discussion
Au cours de ce travail, j’ai réalisé une clef d’identification multi-entrées en proposant une nouvelle analyse du travail de B&FR2005. Sans ce travail remarquable, qui est le résultat d’un nombre d’observation considérable, rien n’aurait été possible. Cette nouvelle lecture de cet ouvrage met en avant des critères non considérés par les auteurs et pourtant pertinents car discriminants. Le développement d’une clef sous Xper2 offre des possibilités d’identification plus souples, plus rapides et plus didactiques (grâce aux nombreuses illustrations) que les clefs dichotomiques à entrées régionales proposées par les auteurs. Cela permet également d’identifier les *Cecropia* lorsqu’ils sont exotiques.  

Néanmoins les observations que nous avons faites en Guyane montrent que l’outil ne fait tout. Notre état de connaissance sur les *Cecropia* reste faible comme le soulignent B&FR2005 dans leur introduction. Pour mémoire, 22.54% des états restent non décrits dans la matrice de caractère que j’ai synthétisée. Ensuite, nous avons vu que la variabilité phénotypique des espèces est parfois sous-évaluée en raison du nombre limité d’échantillon sur lequel pouvaient s’appuyer B&FR2005 dans les herbiers internationaux. Mais surtout, certains morphotypes ne trouvent pas toujours de correspondance dans les 61 espèces décrites. Pour certains spécimens de Guyane, où nous avons pu attribuer une identification, alors nous nous sommes parfois confronté à une incohérence géographique, l’espèce attribuée ayant une aire de répartition très éloignée.  

Les causes de ces problèmes peuvent être multiples. Premièrement, il est fort probable qu’il reste des espèces de *Cecropia* à découvrir. Ensuite, comme le souligne @Webber2011, il est probable qu’il y ait des phénomènes d’hybridations qui rajoutent localement de la variabilité. L’individu observé sur la piste de Counami (Fig. \@ref(fig:fig12)) pourrait en être un exemple dans le sens que nous n’avons pas été capable de retrouver un morphotype similaire là ou il avait été échantillonné. Enfin, il ne faut pas perdre de vue que la circonscription des espèces proposée par B&FR2005 puisse dans certain cas être erronée. Une approche moléculaire fait aujourd’hui cruellement défaut. Cependant, une telle approche ne pourra venir qu’en complément d’une étude taxonomique sérieuse et pour cela, nous avons besoin de nouvelles observations l’échelle de l’aire de répartition du genre.  

Les *Cecropia* sont très peu récoltés pour être envoyé dans les herbiers internationaux. Pour beaucoup de prospecteurs, ce sont des banalités. Là où plusieurs espèces sont présentes, ils n’en voit souvent qu’une seule [@Berg2005]. Les fourmis agressives qui les habitent, la grande dimension des feuilles difficile à mettre en presse, la dioécie sont autant d’obstacles qui freinent leur récolte. Dans ce travail, j’ai montré que la grande majorité des caractères nécessaires à discriminer les espèces, sont observables sur un jeu d’une dizaine de photographies représentant des vues judicieusement choisies. Il est toujours plus délicat de demander à un collègue de mettre en presse et d’envoyer un échantillon d’herbier plutôt que de lui demander quelques photographies qu’il est possible transférer rapidement via internet. Je pense qu’un ‘appel à photographie’ auprès d’une large communauté pourrait trouver un écho positif et nous permettre de collecter rapidement de nouvelles données. C’est en quelque sorte ce que nous avons fait en demandant à plusieurs collègues leur photographies pour créer notre photothèque et les réponse furent toujours positives. Il suffit juste de stimuler de nouvelles prises de vue suivant un protocole un peu plus cadré. On peut voir cela comme des sciences citoyennes ou en complément de la communauté scientifique, des amateurs volontaires, des amateurs éclairés, des spécialistes à la retraite, etc. sont mis à contribution. Plusieurs niveaux pourraient être envisagés depuis la simple prise de photographique jusqu'à la récolte d’un herbier et une descrtiption détaillée des caractères sur la fiche que je propose en annexe 3 et annexe 4. Au travers d’une vitrine que pourrait être un site internet dédié à la tribu, nous pourrions ainsi récolter de quoi construire une matrice de caractère à l’échelle des spécimens et retravailler la circonscription des espèces et les source de leur variabilité phénotypique. Il serait particulièrement intéressant de travailler plus sérieusement la question de la variation des caractères au cours de l’ontogénie. Par ailleurs, les diamètres de pétiole, de pédoncule d’inflorescences ou d’épis varient beaucoup de l’état frai à l’état déshydraté si bien que les valeurs renseignées par B&FR2005 peuvent induire des biais lors de l’identification de matériel frais. La récolte de données en frai et en sec et la recherche de règles de conversion serait également à travailler. La cerise sur le gâteau serait évidemment d’associer pour chaque spécimen un échantillon ADN permettant de comparer variabilité morphométrique et moléculaire.
\pagebreak
