# Conclusion
Les outils d’aide à l’identification connaissent un grand succès depuis une dizaine d’années car ils permettent de rendre la tache bien plus facile qu’avec des clefs dichotomiques. Ce travail sur le genre *Cecropia* n’est qu’une illustration supplémentaire de la performance de ces outils. Une prochaine étape pourrait être de travailler sur la plate-forme IDAO qui s’affranchit complètement des définitions botaniques pour raisonner principalement par l’image, au travers de « portraits-robots ». Quoi qu’il en soit, ces outils doivent à présent se nourrir de données de terrain pour gagner en précision et en efficacité. Nous l’avons vu, notre méconnaissance du genre rend l’identification de certains spécimens difficile. En Guyane française, qui comporte relativement peu d’espèces par rapport à des pays comme la Colombie, les choses ne sont pas si claires que cela. En dehors de *C. obtusa, C. sciadophylla* et *C. palmata* les autres espèces ont été très peu échantillonnées et sur la nouvelle route st-Laurent-Apatou plusieurs morphotypes ne sont pas identifiés. Ce travail donne de premières pistes pour travailler en réseau et compléter la matrice de caractères.
\pagebreak